// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...]').default>>>>
    }
    '/api/academic_year/academic_years': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/academic_year/academic_years.get').default>>>>
    }
    '/api/academic_year/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/academic_year/create.post').default>>>>
    }
    '/api/academic_year/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/academic_year/edit.put').default>>>>
    }
    '/api/academic_year/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/academic_year/remove.delete').default>>>>
    }
    '/api/grade_group/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade_group/create.post').default>>>>
    }
    '/api/grade_group/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade_group/edit.put').default>>>>
    }
    '/api/grade_group/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade_group/remove.delete').default>>>>
    }
    '/api/grade/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade/create.post').default>>>>
    }
    '/api/grade/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade/edit.put').default>>>>
    }
    '/api/grade/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grade/remove.delete').default>>>>
    }
    '/api/pole_average/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pole_average/create.post').default>>>>
    }
    '/api/pole_average/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pole_average/edit.put').default>>>>
    }
    '/api/pole_average/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pole_average/remove.delete').default>>>>
    }
    '/api/semester/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/semester/create.post').default>>>>
    }
    '/api/semester/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/semester/edit.put').default>>>>
    }
    '/api/semester/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/semester/remove.delete').default>>>>
    }
    '/api/subject/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subject/create.post').default>>>>
    }
    '/api/subject/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subject/edit.put').default>>>>
    }
    '/api/subject/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subject/remove.delete').default>>>>
    }
    '/api/unit/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unit/create.post').default>>>>
    }
    '/api/unit/edit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unit/edit.put').default>>>>
    }
    '/api/unit/remove': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unit/remove.delete').default>>>>
    }
    '/api/user/authorization': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/authorization').default>>>>
    }
    '/api/user/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/login.post').default>>>>
    }
    '/api/user/ownself': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/ownself.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/ownself.get').default>>>>
    }
    '/api/user/password': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/password.put').default>>>>
    }
    '/api/user/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/register.post').default>>>>
    }
    '/api/user/rename': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/rename.put').default>>>>
    }
    '/api/user/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/users.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}